#!/usr/bin/env php
<?php
// Run the metric checks directly from CLI without the Drupal harness


// I am invoked from within the larger project, so I probably don't have my own vendor dir here.
// Try to find the parent autoload.
$autoloadPath = getcwd();
while ($autoloadPath !== '/') {
  if (file_exists($autoloadPath . '/vendor/autoload.php')) {
    require $autoloadPath . '/vendor/autoload.php';
    break;
  }
  if (file_exists($autoloadPath . '/autoload.php')) {
    require $autoloadPath . '/autoload.php';
    break;
  }
  $autoloadPath = dirname($autoloadPath);
}



use Symfony\Component\Console\Application;
use Drupal\platformsh_project\Commands\CheckCommand;
use Drupal\platformsh_project\Commands\PingCheckCommand;

$application = new Application('Project Check CLI', '1.0.0');

// Register the available check commands.
$command = new PingCheckCommand();
$application->add($command);
$command = new CheckCommand();
$application->add($command);

$application->run();
