# A template. Substitute the actual bundle ID for mentions of 'bundle'
langcode: en
status: true
dependencies:
  config:
    - field.storage.metric.requirement
    - paragraphs.paragraphs_type.requirement
    - platformsh_project.metric_type.bundle
  module:
    - entity_reference_revisions
  enforced: # makes this go away on uninstall
    module:
      - platformsh_project
id: metric.bundle.requirement
field_name: requirement
entity_type: metric
bundle: bundle
label: Requirement
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:paragraph'
  handler_settings:
    target_bundles:
      requirement: requirement
    negate: 0
    target_bundles_drag_drop:
      requirement:
        weight: 2
        enabled: true
field_type: entity_reference_revisions
